module.exports = {
  purge: {
    enabled: false,
  },
  theme: {
    extend: {
      fontFamily: {
        thin: ["NorthvoltSansPro-Thin", "helvetica neue"],
        light: ["NorthvoltSansPro-Light", "helvetica neue"],
        medium: ["NorthvoltSansPro-Medium", "helvetica neue"],
        regular: ["NorthvoltSansPro-Regular", "helvetica neue"],
        bold: ["NorthvoltSansPro-Bold", "helvetica neue"],
        xbold: ["NorthvoltSansPro-ExtraBold", "helvetica neue"],
        heavy: ["NorthvoltSansPro-Black", "helvetica neue"],
      },
      fontSize: {
        "3xl": ["100px", "1.15"],
        "2xl": ["55px", "60px"],
        xl: ["43px", "1.15"],
        h1: ["var(--f-h1--size)", "var(--f-h1--lineHeight)"],
        h2: ["var(--f-h2--size)", "var(--f-h2--lineHeight)"],
        h3: ["var(--f-h3--size)", "var(--f-h3--lineHeight)"],
        h4: ["var(--f-h4--size)", "var(--f-h4--lineHeight)"],
        h5: ["var(--f-h5--size)", "var(--f-h5--lineHeight)"],
        h6: ["var(--f-h6--size)", "var(--f-h6--lineHeight)"],
      },
      maxWidth: {
        "prose-50": "50ch",
      },
      height: {
        "screen-80": "80vh",
        "screen-50": "50vh",
      },
    },
    screens: {
      sm: "320px",
      "sm-only": { max: "767px" },
      md: "768px",
      "md-max": { max: "1239px" },
      "md-only": { min: "768", max: "1239px" },
      lg: "1240px",
    },
    spacing: {
      0: 0,
      1: "var(--unit-1)",
      2: "calc(var(--unit-1) * 2)",
      3: "calc(var(--unit-1) * 3)",
      4: "calc(var(--unit-1) * 4)",
      5: "calc(var(--unit-1) * 5)",
      6: "calc(var(--unit-1) * 6)",
      7: "calc(var(--unit-1) * 7)",
      8: "calc(var(--unit-1) * 8)",
      9: "calc(var(--unit-1) * 9)",
      10: "calc(var(--unit-1) * 10)",
      11: "calc(var(--unit-1) * 11)",
      12: "calc(var(--unit-1) * 12)",
      13: "calc(var(--unit-1) * 13)",
      14: "calc(var(--unit-1) * 14)",
      15: "calc(var(--unit-1) * 15)",
      16: "calc(var(--unit-1) * 16)",
      17: "calc(var(--unit-1) * 17)",
      18: "calc(var(--unit-1) * 18)",
      19: "calc(var(--unit-1) * 19)",
      20: "calc(var(--unit-1) * 20)",
      a: "var(--unit-a)",
      b: "var(--unit-b)",
      c: "var(--unit-c)",
      d: "var(--unit-d)",
      e: "var(--unit-e)",
      f: "var(--unit-f)",
      g: "var(--unit-g)",
    },
    colors: {
      transparent: "transparent",
      black: "var(--c-black)",
      "black-80": "var(--c-black-80)",
      "black-60": "var(--c-black-60)",
      "black-40": "var(--c-black-40)",
      "black-20": "var(--c-black-20)",
      blue: "var(--c-blue)",
      "blue-75": "var(--c-blue-75)",
      "blue-50": "var(--c-blue-50)",
      "blue-20": "var(--c-blue-20)",
      cyan: "var(--c-cyan)",
      "cyan-75": "var(--c-cyan-75)",
      "cyan-50": "var(--c-cyan-50)",
      "cyan-20": "var(--c-cyan-20)",
      "black-40": "rgba(0,0,0,.4)",
      wafer: "var(--c-wafer)",
      "wafer-75": "var(--c-wafer-75)",
      "wafer-50": "var(--c-wafer-50)",
      "wafer-20": "var(--c-wafer-20)",
      "black-40": "rgba(0,0,0,.4)",
      orange: "var(--c-orange)",
      "orange-75": "var(--c-orange-75)",
      "orange-50": "var(--c-orange-50)",
      "orange-20": "var(--c-orange-20)",
      "black-40": "rgba(0,0,0,.4)",
      rust: "var(--c-rust)",
      "rust-75": "var(--c-rust-75)",
      "rust-50": "var(--c-rust-50)",
      "rust-20": "var(--c-rust-20)",
      "black-40": "rgba(0,0,0,.4)",
      "grey-500": "var(--c-grey-500)",
      current: "currentColor",
      brand: "var(--c-brand)",
      navy: "var(--c-navy)",
      seaGreen: "var(--c-seaGreen)",
      seaGreenDark: "var(--c-seaGreen--dark)",
      freshBlue: "var(--c-freshBlue)",
      green: "var(--c-green)",
      yellow: "var(--c-yellow)",
      orange: "var(--c-orange)",
      lavender: "var(--c-lavender)",
      cream: "var(--c-cream)",
      tan: "var(--c-tan)",
      ivory: "var(--c-ivory)",
      porcelain: "var(--c-porcelain)",
      charcoal: "var(--c-charcoal)",
      iron: "var(--c-iron)",
      steel: "var(--c-steel)",
      smoke: "var(--c-smoke)",
      fog: "var(--c-fog)",
      white: "var(--c-ivory)",
      footerBg: "var(--c-footerBg)",
      techGradientFrom: "#4C8CF6",
      techGradientTo: "#2B2C58",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      5: "5px",
      6: "6px",
      7: "7px",
      8: "8px",
      9: "9px",
      10: "10px",
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/aspect-ratio")],
  corePlugins: {
    fontWeight: false,
    container: false,
  },
};
